### ISSUE TITLE
Order variables by factor levels for feature importance plot

### ISSUE THREAD

**Issue by JeffreyRStevens** [ModelOriented/ingredients#146]
Wonderful package! Do you think it would be possible to allow users to order the variables in the feature importance plots by factor level? Basically, this would involve adding a third option to `desc_sorting` to indicate not to sort based on mean feature importance. It should be a pretty easy fix. I've worked up a pull request if you're interested.

**Comment by hbaniecki** [comment]
Hi, `desc_sorting` is of `logical` type with two intuitive parameter values. I believe the change you propose requires adding a new parameter. 

Overall, the idea of `ggplot2` is to easily extend/update plots. What do you think about the following solution:
```r
library(DALEX)

df <- mtcars[, c('mpg', 'cyl', 'disp', 'hp')]
model <- lm(mpg ~ ., data = df)
explainer <- explain(model, data = df[,-1], y = df[,1])
fi <- feature_importance(explainer)
plot(fi)

library(ggplot2)
plot(fi) + scale_x_discrete(limits=c("cyl", "disp", "hp"))
```

Note that I use `scale_x_...` because the plot has already applied `coord_flip()`.

**Comment by JeffreyRStevens** [comment]
@hbaniecki, very nice workaround! Yes, this is much easier than messing with `desc_sorting`. Many thanks!
