### ISSUE TITLE
DALEXverse 0.19.8 release summer 2019

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/ingredients#50]
DALEXverse 0.19.8 release summer 2019

# Integration

- [x] readability: vignettes
- [x] readability: NEWS
- [x] readability: DESCRIPTION
- [x] consistency: pkgdown website
- [x] consistency: entry at DrWhy.AI webpage

assigned: @pbiecek

# Code review

- [x] consistency: names of functions 
- [x] consistency: names of files
- [x] consistency: names of variables in functions (local and global)
- [x] length: functions
- [ ] readability: code (comments, constructions)

assigned: @hbaniecki 

# Feature review

- [x] readability: documentation (title, description, details)
- [x] readability: examples (relevant, complete, with comments)
- [ ] reproducibility: tests (code coverage)
- [x] links to functions: \code 

assigned: @AdamIzdebski

**Comment by hbaniecki** [comment]
-1. readability: DESCRIPTION change URL to https://github.com/ModelOriented/ingredients
 update demo.png in README

0. in many places in documentation `x` should be documented as explainer first and
 `data/y/predict`_function should be placed as last parameters in function
ex: conditional_dependency.R, feature_importance.R, ...

1. placement of `...` parameter is inconsistent across many functions 
- accumulated_dependency.R 
- aspect_importance.R
- conditional_dependency.R
- feature_importance.R
- partial_dependency.R
- more

2. parameters in documentation are in different order than in function call
- aggregate_profiles.R
- cluster_profiles.R

3. change parameter name
- aspect_importance.R `aspects_list` could be just `aspects` (like `variables`)
- plot_ceteris_paribus_2d_explainer.R `split_ncol` to `facet_ncol`

4. In many functions `N` and `B` are beeing used. There is no consistency 

5. check `x` class and produce error in calculate_oscillations.R could also appear in
- aggregate_profiles.R
- cluster_profiles.R 
- plot_aggregated_profiles_explainer.R
- plot_ceteris_paribus_2d_explainer.R
- plot_ceteris_paribus_explainer.R
- more

6. `=` instead of `<-`
- https://github.com/ModelOriented/ingredients/blob/master/R/calculate_oscillations.R#L61
- https://github.com/ModelOriented/ingredients/blob/master/R/ceteris_paribus_2d.R#L88
- https://github.com/ModelOriented/ingredients/blob/master/R/cluster_profiles.R#L138
- https://github.com/ModelOriented/ingredients/blob/master/R/aspect_importance.R#L171
- https://github.com/ModelOriented/ingredients/blob/master/R/ceteris_paribus.R#L167
- https://github.com/ModelOriented/ingredients/blob/master/R/describe_aggregatedprofiles.R#L74
- https://github.com/ModelOriented/ingredients/blob/master/R/describe_ceterisparibus.R#L102
- https://github.com/ModelOriented/ingredients/blob/master/R/describe_featureimportance.R#L56
- https://github.com/ModelOriented/ingredients/blob/master/R/describe_ceterisparibus.R#L312
- https://github.com/ModelOriented/ingredients/blob/master/R/describe_ceterisparibus.R#L338 (all `sufix =`) 

7. CODE NOTES
- `ifelse` https://github.com/ModelOriented/ingredients/blob/master/R/describe_aggregatedprofiles.R#L267
- `->` https://github.com/ModelOriented/ingredients/blob/master/R/calculate_oscillations.R#L53
- could use some comments  https://github.com/ModelOriented/ingredients/blob/master/R/ceteris_paribus_2d.R
- could use some comments https://github.com/ModelOriented/ingredients/blob/master/R/describe_ceterisparibus.R#L307
- could use some comments https://github.com/ModelOriented/ingredients/blob/master/R/describe_ceterisparibus.R#L321
- **this is prone to ERROR - needs to be changed** https://github.com/ModelOriented/ingredients/blob/master/R/conditional_dependency.R#L84 
and https://github.com/ModelOriented/ingredients/blob/master/R/conditional_dependency.R#L85
- take care of class logical (?) https://github.com/ModelOriented/ingredients/blob/master/R/describe_aggregatedprofiles.R#L56
https://github.com/ModelOriented/ingredients/blob/master/R/describe_ceterisparibus.R#L82
- add `predict` as default https://github.com/ModelOriented/ingredients/blob/master/R/feature_importance.R#L162
- this could be default parameter value in function call https://github.com/ModelOriented/ingredients/blob/master/R/plotD3_aggregated_profiles_explainer.R#L150 the same in other plotD3

8. calculate_variable_profile.R has no support for `DALEX explainer use` + sad documentation

9. ceteris_paribus_2d.R all parameters are inconsistent with the rest of ingredients

10. describe.R could be deleted?

11. Change file name:
- describe_aggregatedprofiles.R
- describe_ceterisparibus.R
- describe_featureimportance.R

- plotD3_aggregated_profiles_explainer.R
- plotD3_ceteris_paribus_explainer.R
- plotD3_feature_importance_explainer.R
- plot_aggregated_profiles_explainer.R
- and more..... (cut `_explainer` everywhere)

- cut `s`: print_ceteris_paribus_descriptions.R 

12. weird/no parameter documentation
- describe_aggregatedprofiles.R
- describe_ceterisparibus.R
- describe_featureimportance.R
https://github.com/ModelOriented/ingredients/blob/master/R/select_samples.R#L11

13. ingredients has theme_drwhy.R

14. add `@noRd` to not exported functions

**Comment by AdamIzdebski** [comment]
(Key functions)
**readability: documentation (title, description, details)**

 - `feature_importance()` 
    1. Make descriptions consistent with https://pbiecek.github.io/PM_VEE/
possible change: "This function calculates permutation based feature importance."
    2. Arguments:
       `x` should the description include model or just class explainer (Argument in favour of deleting the model option: function `feature_importance` needs arguments that are additional and are on the low end of the list in order to work with model.)
       typos, 
       'type' possible change "a string specifying which ... . Possible values are ... "
      punctuation is not consistent it's either a comma or dot after argument class and before the description
 - `ceteris_paribus()` 
   3. description: The first sentence should communicate what the function does. possible change: "This function calculates a one dimensional ceteris paribus profile for the selected variables."
   4. Arguments order is not consistent, new_observation is needed for the function to work and should be second in order. 
      `new_observation` should the observation contain the decision (y) variable?  
 - `calculate_oscillations()` 2 applies
 - `ceteris_paribus_2d()` description that could serve as an example for other functions, arguments 'variables' in not clear how to use
 - `partial_dependency()` 2 applies, 
 - `conditional_dependency()` 1,3`

 **readability: examples (relevant, complete, with comments)**
 
 - `feature_importance()` if `x` can be a model, then an example how to use the function with models should be added
 - `ceteris_paribus()` 5. examples could be commented, more different arguments could be demonstrated on the same explainer
 - `ceteris_paribus_2d()` 6. example for using variables argument should be provided, it is not always working
 - `partial_dependency()` 5 and 6 applies
 - `conditional_dependency()` 5,6
 - `aggregate_profiles()` warnings are generated, 6

**reproducibility: tests (code coverage)**

 - describe_aggregated_profiles.R - test on inputs with continuous variable 
 - aggregated_profiles.R - test accumulated profiles on non null groups and non-numeric variables, test conditional_profiles for nonnumeric variables, those examples can be ploted too.
  
**links to functions: \code**
 All functions need link to DALEX::explain in arguments 
argument x linked to `ceteris_paribus()` in `aggregate_profiles()` , `accumulated_dependency()`

**Comment by maksymiuks** [comment]
Try to get rid of titanic package suggest

**Comment by hbaniecki** [comment]
add demo gif to ingredients and iBreakDown
